/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],

  theme: {
    extend: {
        "colors": {
            "background": "#f8f9ff",
            "on-surface": "#0f1c2d",
            "tertiary-container": "#00412b",
            "hvac-warm": "#FF9500",
            "surface-container-low": "#eff4ff",
            "error": "#ba1a1a",
            "outline-variant": "#c0c9c1",
            "inverse-on-surface": "#eaf1ff",
            "surface-container": "#e6eeff",
            "secondary": "#a43c16",
            "surface-dim": "#cddbf1",
            "on-tertiary-fixed": "#002114",
            "inverse-surface": "#243142",
            "surface-tint": "#34684f",
            "on-secondary": "#ffffff",
            "tertiary": "#00291a",
            "on-secondary-container": "#6d1e00",
            "on-secondary-fixed": "#390b00",
            "surface-container-high": "#dce9ff",
            "surface": "#f8f9ff",
            "tertiary-fixed-dim": "#8ad6b0",
            "primary-container": "#05412b",
            "on-primary-fixed-variant": "#1a5039",
            "primary-fixed": "#b7efcf",
            "on-tertiary": "#ffffff",
            "surface-variant": "#d6e3fa",
            "tertiary-fixed": "#a6f3cb",
            "primary": "#002919",
            "surface-container-lowest": "#ffffff",
            "on-primary": "#ffffff",
            "secondary-container": "#fe7e53",
            "on-error-container": "#93000a",
            "on-background": "#0f1c2d",
            "error-container": "#ffdad6",
            "slate-surface": "#F8FAFC",
            "surface-container-highest": "#d6e3fa",
            "on-primary-fixed": "#002113",
            "on-surface-variant": "#404943",
            "on-tertiary-container": "#65b08d",
            "secondary-fixed-dim": "#ffb59d",
            "on-error": "#ffffff",
            "primary-fixed-dim": "#9bd3b4",
            "outline": "#717973",
            "on-primary-container": "#77ad91",
            "on-tertiary-fixed-variant": "#005137",
            "hvac-cool": "#0A84FF",
            "secondary-fixed": "#ffdbd0",
            "surface-bright": "#f8f9ff",
            "border-muted": "#E2E8F0",
            "on-secondary-fixed-variant": "#842600",
            "inverse-primary": "#9bd3b4"
        },
        "borderRadius": {
            "DEFAULT": "0.125rem",
            "lg": "0.25rem",
            "xl": "0.5rem",
            "full": "0.75rem"
        },
        "spacing": {
            "grid-gutter": "16px",
            "table-cell-padding": "12px 16px",
            "base": "4px",
            "grid-margin": "24px",
            "step-indicator-gap": "32px"
        },
        "fontFamily": {
            "body-sm": ["Inter"],
            "data-mono": ["Inter"],
            "headline-sm": ["Hanken Grotesk"],
            "body-lg": ["Inter"],
            "headline-md": ["Hanken Grotesk"],
            "label-sm": ["Inter"],
            "headline-lg": ["Hanken Grotesk"],
            "label-md": ["Inter"],
            "body-md": ["Inter"],
            "display-lg": ["Hanken Grotesk"]
        },
        "fontSize": {
            "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
            "data-mono": ["14px", { "lineHeight": "20px", "letterSpacing": "-0.01em", "fontWeight": "500" }],
            "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
            "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
            "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
            "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
            "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "600" }],
            "label-md": ["14px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
            "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
            "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }]
        }
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
